name: luckywheel
description: "A new Flutter project."
publish_to: 'none'  # Change this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.2.0
  get: ^4.6.6
  intl: ^0.19.0
  rxdart: ^0.28.0
  flutter_fortune_wheel: ^1.3.1
  connectivity_plus: ^6.0.4
  shared_preferences: ^2.3.1
  url_launcher: ^6.3.0
  share_plus: ^10.0.0
  clipboard: ^0.1.3
  google_mobile_ads: ^5.1.0
  audioplayers: ^6.0.0
  provider: ^6.1.2
  flutter_countdown_timer: ^4.1.0
  fluttertoast: ^8.2.6
  flutter_launcher_icons: ^0.13.1
  flutter_automation: ^2.0.0
  change_app_package_name: ^1.3.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptiv_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
  #       - asset: fonts/YourFont-Bold.ttf
  #         weight: 700